apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-runner
spec:
  selector:
    matchLabels:
      app: maintenance-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: maintenance-deployment
    spec:
      containers:
      - name: maintenance-deployment
        image: maintenance-deployment:latest
        imagePullPolicy: Never
        env:
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "mydb"
        - name: APP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
