apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-runner
  namespace: maintenance
spec:
  selector:
    matchLabels:
      app: maintenance-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: maintenance-deployment
    spec:
      containers:
      - name: maintenance-deployment
        image: maintenance-deployment:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 3000
        - name: mysql
          containerPort: 3306
      env:
        - name: LOCALHOST
          value: "mysql-deployment.maintenance.svc.cluster.local"

---
apiVersion: v1
kind: Service
metadata:
  name: maintenance-deployment
  namespace: maintenance
spec:
  type: ClusterIP
  selector:
    app: maintenance-deployment
  ports:
    - name: http
      port: 3000
      targetPort: 3000