apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: maintenance
spec:
  selector:
    matchLabels:
      app: mysql-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
      - name: mysql-deployment
        image: mysql:5.7
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: test
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-deployment
  namespace: maintenance
spec:
  type: ClusterIP
  selector:
    app: mysql-deployment
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
      targetPort: 3306